// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/calculations/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculations/[id].get').default>>>>
    }
    '/api/calculations/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculations/create.post').default>>>>
    }
    '/api/calculations/delete': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculations/delete.delete').default>>>>
    }
    '/api/calculations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculations/index.get').default>>>>
    }
    '/api/calculations/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/calculations/update.put').default>>>>
    }
    '/api/gatepass/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gatepass/create.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_openapi.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/openapi').default>>>>
    }
    '/_scalar': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/scalar').default>>>>
    }
    '/_swagger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nitropack/dist/runtime/internal/routes/swagger').default>>>>
    }
  }
}
export {}