<template>
  <div v-if="gatePass" id="gatePassAnchor" class="gate-pass-print-only">
    <div class="header-section text-center border-bottom border-2 border-dark pb-3 mb-3">
      <img src="/logo.png" style="height: 50px; margin-bottom: 10px;">
      <div class="text-uppercase fw-bold small">Gate Pass | ID: {{ gatePass.passNumber }}</div>
    </div>

    <div class="row mb-3 gx-2">
      <div class="col-6">
        <div class="small fw-bold text-uppercase text-muted">Customer</div>
        <div class="fs-6 fw-bold">{{ gatePass.customerName || 'N/A' }}</div>
      </div>
      <div class="col-6 text-end">
        <div class="small fw-bold text-uppercase text-muted">Date</div>
        <div class="fs-6">{{ formatDate(gatePass.createdAt) }}</div>
      </div>
    </div>

    <!-- Set Image if available -->
    <div v-if="gatePass.calculation.setImageUrl" class="text-center mb-3">
        <img :src="gatePass.calculation.setImageUrl" style="max-height: 200px; max-width: 100%; object-fit: contain;">
    </div>

    <div class="mb-3">
      <div class="small fw-bold text-uppercase text-muted border-bottom border-dark mb-1">Set Details</div>
      <div class="fs-6 fw-bold">{{ gatePass.calculation.setName }}</div>
    </div>

    <div class="table-responsive">
      <table class="table table-bordered align-middle table-sm border-dark">
        <thead class="table-light text-center">
          <tr>
            <th class="fw-bold">Colour</th>
            <th class="fw-bold">Sets</th>
            <th class="fw-bold" v-for="type in allMotiTypes" :key="type">{{ type }}</th>
          </tr>
        </thead>
        <tbody class="text-center">
          <tr v-for="colour in gatePass.calculation.colours" :key="colour.id">
            <td class="text-start fw-bold text-nowrap">{{ colour.name }}</td>
            <td>{{ colour.qty }}</td>
            <td v-for="type in allMotiTypes" :key="type">
              {{ getLariForType(colour, type) }}
            </td>
          </tr>
        </tbody>
        <tfoot class="table-light text-center fw-bold">
          <tr>
            <td>TOTAL</td>
            <td>{{ totalSets }}</td>
            <td v-for="type in allMotiTypes" :key="type">
              {{ Math.round(totalLariByType[type]) }}
            </td>
          </tr>
        </tfoot>
      </table>
    </div>

    <div class="mt-4 pt-4 border-top border-dashed text-center text-muted small note">
      Generated by Moti Calculator App
    </div>
  </div>
</template>

<script setup>
const props = defineProps({
  gatePass: {
    type: Object,
    required: true
  }
})

const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

const allMotiTypes = computed(() => {
  if (!props.gatePass) return []
  const types = new Set()
  props.gatePass.calculation.motiRequirements.forEach(m => types.add(m.type))
  props.gatePass.calculation.colours.forEach(c => {
    if (c.hasCustom) {
      c.customMotis.forEach(m => types.add(m.type))
    }
  })
  return Array.from(types).sort()
})

const getLariForType = (colour, type) => {
  const motis = colour.hasCustom ? colour.customMotis : props.gatePass.calculation.motiRequirements
  const moti = motis.find(m => m.type === type)
  // Round amounts
  return moti ? Math.round(moti.lariPerSet * colour.qty) : '0'
}

const totalSets = computed(() => {
  if (!props.gatePass) return 0
  return props.gatePass.calculation.colours.reduce((sum, c) => sum + c.qty, 0)
})

const totalLariByType = computed(() => {
  const totals = {}
  allMotiTypes.value.forEach(type => {
    totals[type] = 0
    props.gatePass.calculation.colours.forEach(c => {
      const motis = c.hasCustom ? c.customMotis : props.gatePass.calculation.motiRequirements
      const moti = motis.find(m => m.type === type)
      if (moti) totals[type] += (moti.lariPerSet * c.qty)
    })
  })
  return totals
})
</script>

<style scoped>
/* Print Specific Styles */
@media print {
  @page {
    size: auto;
    margin: 0mm;
  }
  
  body {
    margin: 0;
    padding: 0;
  }

  /* Robust hiding of everything else is hard if deeply nested, so we make this component cover everything */
  .gate-pass-print-only {
    display: block !important;
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    z-index: 99999;
    background: white;
    color: black;
    padding: 0;
    margin: 0;
  }
}
@media print {
  body * {
    visibility: hidden;
  }
  
  .gate-pass-print-only, .gate-pass-print-only * {
    visibility: visible;
  }

  .gate-pass-print-only {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    margin: 0;
    padding: 20px; /* Safe padding for print */
    background: white;
  }
  
  /* Reset table colors */
  .table-bordered, .table-bordered td, .table-bordered th {
    border: 1px solid black !important;
  }

  .table-light {
    background-color: transparent !important;
    color: black !important;
  }
}

/* Hide on screen if needed, usually managed by parent with v-show/if or CSS */
.gate-pass-print-only {
    background: white;
}
</style>
