<template>
  <div class="container px-2 py-3 px-md-3 py-md-4">
    <div class="card border-0 shadow-lg rounded-4 overflow-hidden" :class="isDarkMode ? 'bg-dark-card border-secondary' : 'bg-white'">
      <div class="card-header border-0 p-4 text-center" :class="isDarkMode ? 'bg-secondary text-white' : 'bg-primary text-white'">
        <h1 class="h3 mb-0">📄 Gate Pass Management</h1>
      </div>

      <div class="card-body p-2 p-md-4">
        <div class="card border-0 shadow-sm mb-4">
          <div class="card-body">
            <h3 class="h5 border-bottom pb-2 mb-3">Create New Gate Pass</h3>
            <div class="row g-3">
              <div class="col-md-4">
                <label class="form-label small fw-bold">Select Calculation</label>
                <select v-model="selectedCalcId" class="form-select">
                  <option value="">-- Choose Calculation --</option>
                  <option v-for="calc in calculations" :key="calc.id" :value="calc.id">
                    {{ calc.setName }} ({{ new Date(calc.createdAt).toLocaleDateString() }})
                  </option>
                </select>
              </div>
              <div class="col-md-4">
                <label class="form-label small fw-bold">Gate Pass Number</label>
                <input v-model="passDetails.passNumber" type="text" class="form-control" placeholder="GP-001">
              </div>
              <div class="col-md-4">
                <label class="form-label small fw-bold">Customer Name</label>
                <input v-model="passDetails.customerName" type="text" class="form-control py-2" placeholder="Enter name">
              </div>
            </div>
            <button @click="generatePass" class="btn btn-success mt-4 px-4" :disabled="!selectedCalcId || loading">
              <span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>
              Create & Preview
            </button>
          </div>
        </div>

        <!-- PREVIEW -->
        <div v-if="gatePass" id="gatePassAnchor" class="gate-pass-preview border border-2 border-primary rounded-4 p-3 p-md-5 bg-white shadow-sm mt-4">
          <div class="text-center border-bottom border-2 border-primary pb-4 mb-4">
            <img src="../public/logo.png" style="height: 50px; margin-bottom: 10px;">
            <div class="text-muted small">GATE PASS | ID: {{ gatePass.passNumber }}</div>
          </div>

          <div class="row mb-4">
            <div class="col-6">
              <div class="small fw-bold text-uppercase text-muted">Customer</div>
              <div class="fs-5">{{ gatePass.customerName || 'N/A' }}</div>
            </div>
            <div class="col-6 text-end">
              <div class="small fw-bold text-uppercase text-muted">Date</div>
              <div class="fs-5">{{ new Date(gatePass.createdAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) }}</div>
            </div>
          </div>

          <div class="mb-4">
            <div class="small fw-bold text-uppercase text-muted border-bottom mb-2">Set Details</div>
            <div class="fs-5 fw-bold">{{ gatePass.calculation.setName }}</div>
          </div>

          <div class="table-responsive">
            <table class="table table-bordered align-middle">
              <thead class="table-primary text-center">
                <tr>
                  <th>Colour</th>
                  <th>Sets</th>
                  <th v-for="type in allMotiTypes" :key="type">{{ type }} (Lari)</th>
                </tr>
              </thead>
              <tbody class="text-center">
                <tr v-for="colour in gatePass.calculation.colours" :key="colour.id">
                  <td class="text-start fw-bold">{{ colour.name }}</td>
                  <td>{{ colour.qty }}</td>
                  <td v-for="type in allMotiTypes" :key="type">
                    {{ Math.round(getLariForType(colour, type)) }}
                  </td>
                </tr>
              </tbody>
              <tfoot class="table-light text-center fw-bold">
                <tr>
                  <td>TOTAL</td>
                  <td>{{ totalSets }}</td>
                  <td v-for="type in allMotiTypes" :key="type">
                    {{ Math.round(totalLariByType[type]) }}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>

          <div class="mt-5 pt-4 border-top border-dashed text-center text-muted small">
            Generated by Moti Calculator App
          </div>

          <div class="mt-4 no-print text-center">
            <button @click="printPass" class="btn btn-primary px-5" :disabled="isSharing">
              <span v-if="isSharing" class="spinner-border spinner-border-sm me-2"></span>
              Share / Save PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
    
  <!-- Hidden Print Component - Reusing the unified component -->
  <!-- We use a separate container for native sharing generation that is not 'display: none' but maybe off-screen if needed, 
       but for html2pdf it's safest to use the existing hidden one if we can make it visible during generation, 
       OR just rely on the existing one being d-print-block. 
       Actually html2pdf needs it rendered. d-none elements have 0 dimensions. 
       We will use a special class for the capture element that is visible but absolute positioned off screen or z-indexed behind.
  -->
  <div class="d-none d-print-block">
      <GatePassPrint v-if="gatePass" :gatePass="gatePass" />
  </div>
</template>

<script setup>
import { usePdfShare } from '~/composables/usePdfShare'

const isDarkMode = inject('isDarkMode')
const route = useRoute()
const { data: calculations } = useFetch('/api/calculations')
const selectedCalcId = ref(route.query.id || '')
const loading = ref(false)
const gatePass = ref(null)
const passDetails = ref({
  passNumber: 'GP-' + Math.floor(Math.random() * 1000).toString().padStart(3, '0'),
  customerName: ''
})

const { shareOrDownloadPDF, isSharing } = usePdfShare()

const allMotiTypes = computed(() => {
  if (!gatePass.value) return []
  const types = new Set()
  gatePass.value.calculation.motiRequirements.forEach(m => types.add(m.type))
  gatePass.value.calculation.colours.forEach(c => {
    if (c.hasCustom) {
      c.customMotis.forEach(m => types.add(m.type))
    }
  })
  return Array.from(types).sort()
})

const getLariForType = (colour, type) => {
  const motis = colour.hasCustom ? colour.customMotis : gatePass.value.calculation.motiRequirements
  const moti = motis.find(m => m.type === type)
  return moti ? (moti.lariPerSet * colour.qty).toFixed(2) : '0.00'
}

const totalSets = computed(() => {
  if (!gatePass.value) return 0
  return gatePass.value.calculation.colours.reduce((sum, c) => sum + c.qty, 0)
})

const totalLariByType = computed(() => {
  const totals = {}
  allMotiTypes.value.forEach(type => {
    totals[type] = 0
    gatePass.value.calculation.colours.forEach(c => {
      const motis = c.hasCustom ? c.customMotis : gatePass.value.calculation.motiRequirements
      const moti = motis.find(m => m.type === type)
      if (moti) totals[type] += (moti.lariPerSet * c.qty)
    })
  })
  return totals
})

const generatePass = async () => {
  loading.value = true
  try {
    const res = await $fetch('/api/gatepass/create', {
      method: 'POST',
      body: {
        ...passDetails.value,
        calculationId: selectedCalcId.value
      }
    })
    gatePass.value = res
  } catch (error) {
    alert('Failed to generate gate pass server-side, using local preview.')
    // Local fallback for preview if DB failed
    const calc = calculations.value.find(c => c.id === selectedCalcId.value)
    gatePass.value = {
      ...passDetails.value,
      createdAt: new Date(),
      calculation: calc
    }
  } finally {
    loading.value = false
  }
}

const printPass = async () => {
    if (!gatePass.value) return
    await shareOrDownloadPDF(gatePass.value, 'gatepass', `GatePass-${gatePass.value.passNumber}.pdf`)
}
</script>

<style scoped>
.bg-primary {
  background: var(--primary-gradient) !important;
}
.bg-secondary {
  background: linear-gradient(135deg, #2c3e50 0%, #000000 100%) !important;
}
.bg-dark-card {
  background-color: #1e1e1e !important;
}
.border-dashed {
  border-style: dashed !important;
}


@media print {
  /* Hide everything except the print component which handles its own visibility via body * visibility: hidden strategy in GatePassPrint.vue */
  /* However, since GatePassPrint.vue sets body * to hidden, we don't need to do much here except ensure the component is present. */
  
  /* We just strictly hide the main UI container to prevent it showing up in print */
  .container {
      display: none !important;
  }
}
</style>
